[package]
authors = ["jaywunder <public@jacobwunder.com>"]
name = "otek"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.0"

[dependencies]
lalrpop-util = "0.13.0"
regex = "0.2.1"
